### ISSUE TITLE
Cannot import to IntelliJ 14

### ISSUE THREAD

**Issue by tseglevskiy** [saturday06/gradle-android-scala-plugin#45]
I cannot import the sample/simple project to the fresh IntelliJ14CE. 

Screenshot: https://www.dropbox.com/s/knhfidvnwfdebtp/Screen%20Shot%202015-01-17%20at%2000.37.44.png?dl=0
Log: https://www.dropbox.com/s/qrqg7qmvh4tbyi9/idea.log?dl=0

Is there any ideas?

**Comment by saturday06** [comment]
Please move sample/simple dir to out of gradle-android-scala-plugin dir. IntellijJ's gradle importer reads gradle-android-scala-plugin/gradle/*.properties mistakenly.

**Comment by tseglevskiy** [comment]
I've moved. Import finished without errors, but there is no sources in project. 
https://www.dropbox.com/s/jpkdv9e02ghbz36/Screen%20Shot%202015-01-17%20at%2018.34.41.png?dl=0

Any ideas?

**Comment by saturday06** [comment]
In my IntelliJ 14.0.2 CE on Windows8 64bit, the import works fine as long as Android Studio. I think it's a problem particular to IntelliJ in OSX even if the problem exists deleting `.idea/` , `.gradle/` `build/`, `*.iml`, `*.ipr`

**Comment by saturday06** [comment]
I think this is same issue to https://github.com/saturday06/gradle-android-scala-plugin/issues/50 already closed. If the issue exists yet, please reopen.
