### ISSUE TITLE
AndroidAnnotations generates warnings when using with scala plugin

### ISSUE THREAD

**Issue by xasima** [saturday06/gradle-android-scala-plugin#47]
Please review the comment threads https://github.com/excilys/androidannotations/issues/521 and a separate reduced project https://github.com/xasima/gradle-scala-androidannotations on this issue. 
It seems that androidannotations may have some fault behavior, when scala plugin settings is presented in gradle.build file .

**Comment by saturday06** [comment]
Hi, Thanks for reporting!
This bug has been fixed by v1.3.3 (https://github.com/saturday06/gradle-android-scala-plugin/commit/72f06bc1947c7f0e36c09fb149f380842f392126). Please upgrade the plugin and retry.

**Comment by xasima** [comment]
Yes, this works. thanks!
