### ISSUE TITLE
The Hello World app doesn't set up completely

### ISSUE THREAD

**Issue by GildedHonour** [saturday06/gradle-android-scala-plugin#50]
The Hello World app as it is doesn't set up completely and thus I can't compile it. How can I set it up?

![screen shot 2015-02-11 at 15 37 54](https://cloud.githubusercontent.com/assets/2032888/6144028/3073b974-b204-11e4-909c-c90c2bf3e7dc.png)

**Comment by GildedHonour** [comment]
Also

![screen shot 2015-02-11 at 15 41 38](https://cloud.githubusercontent.com/assets/2032888/6144045/822cd516-b204-11e4-9fc5-acc576cb7ef3.png)

**Comment by saturday06** [comment]
Please copy `sample/hello` directory to another directory out of gradle-android-scala-plugin.
This is because IntelliJ and AndroidStudio can't handle a project with nested gradle wrapper correctly.
I'll fix or avoid it in the future

**Comment by GildedHonour** [comment]
Other errors:
![screen shot 2015-02-11 at 18 26 31](https://cloud.githubusercontent.com/assets/2032888/6146113/c1e90d3e-b21b-11e4-93f0-3c4722e96f17.png)

![screen shot 2015-02-11 at 18 26 37](https://cloud.githubusercontent.com/assets/2032888/6146114/c31e4dcc-b21b-11e4-8ca8-b74cbeb963de.png)

**Comment by GildedHonour** [comment]
When I click on Migrate go Gradle wrapper.... nothing happens, the errors remain.

**Comment by saturday06** [comment]
Hi,
Probabily, I've been fixed this issue in latest master branch. Please pull that branch and retry.

**Comment by GildedHonour** [comment]
When? I download the example today.

**Comment by saturday06** [comment]
About 2 hours ago

**Comment by GildedHonour** [comment]
It compiles but it says "Waiting for device; USB device not found" when I launch it, although the device is connected and I was able to launch this https://github.com/pocorall/hello-scaloid-gradle on it.

**Comment by GildedHonour** [comment]
By the way, it also shows this in the debugger:
```
02-12 00:24:11.762  14243-14243/jp.leafytree.android.hello E/IMGSRV﹕ :0: PVRDRMOpen: TP3, ret = 48
02-12 00:24:11.772  14243-14243/jp.leafytree.android.hello E/IMGSRV﹕ :0: PVRDRMOpen: TP3, ret = 51
02-12 00:24:11.772  14243-14243/jp.leafytree.android.hello E/IMGSRV﹕ :0: PVRDRMOpen: TP3, ret = 52
02-12 00:24:11.772  14243-14243/jp.leafytree.android.hello E/IMGSRV﹕ :0: PVRDRMOpen: TP3, ret = 52
02-12 00:24:11.772  14243-14243/jp.leafytree.android.hello E/IMGSRV﹕ :0: PVRDRMOpen: TP3, ret = 52
02-12 00:24:11.782  14243-14243/jp.leafytree.android.hello E/IMGSRV﹕ :0: PVRDRMOpen: TP3, ret = 54
```

**Comment by saturday06** [comment]
> By the way, it also shows this in the debugger as the errors:
> ```
02-12 00:24:11.762  14243-14243/jp.leafytree.android.hello E/IMGSRV﹕ :0: PVRDRMOpen: TP3, ret = 48
02-12 00:24:11.772  14243-14243/jp.leafytree.android.hello E/IMGSRV﹕ :0: PVRDRMOpen: TP3, ret = 51
02-12 00:24:11.772  14243-14243/jp.leafytree.android.hello E/IMGSRV﹕ :0: PVRDRMOpen: TP3, ret = 52
02-12 00:24:11.772  14243-14243/jp.leafytree.android.hello E/IMGSRV﹕ :0: PVRDRMOpen: TP3, ret = 52
02-12 00:24:11.772  14243-14243/jp.leafytree.android.hello E/IMGSRV﹕ :0: PVRDRMOpen: TP3, ret = 52
02-12 00:24:11.782  14243-14243/jp.leafytree.android.hello E/IMGSRV﹕ :0: PVRDRMOpen: TP3, ret = 54
```
Please create new issue for it. This issue is used for importing error and already closed.
