### ISSUE TITLE
Unable to compile in Android Studio 1.1.0

### ISSUE THREAD

**Issue by impinball** [saturday06/gradle-android-scala-plugin#53]
[This line](https://github.com/saturday06/gradle-android-scala-plugin/blob/master/src/main/groovy/jp/leafytree/gradle/AndroidScalaPlugin.groovy#L211) throws an error resulting in the following message:

```
Error:No such property: bootClasspath for class: com.android.build.gradle.AppPlugin
```

This line breaks starting with Android Gradle Plugin version 1.1.0. Here's how the Groovy Android Plugin works around it: [1](https://github.com/groovy/groovy-android-gradle-plugin/blob/master/src/main/groovy/groovyx/grooid/GroovyAndroidPlugin.groovy#L109-L147), [2](https://github.com/groovy/groovy-android-gradle-plugin/blob/master/src/main/groovy/groovyx/grooid/GroovyAndroidPlugin.groovy#L16-L20), [3](https://github.com/groovy/groovy-android-gradle-plugin/blob/master/src/main/groovy/groovyx/grooid/GroovyAndroidPlugin.groovy#L94).

**Comment by saturday06** [comment]
Thanks for your information!
It'll fix in next version.

**Comment by sgrif** [comment]
Any updates on this? I'd love to migrate over to this from the horrendous sbt plugin.

**Comment by saturday06** [comment]
Fixed version was released!

**Comment by sgrif** [comment]
Thank you so much for your prompt with on this! <3
