### ISSUE TITLE
Could not resolve all dependencies for configuration

### ISSUE THREAD

**Issue by ulx** [saturday06/gradle-android-scala-plugin#62]
Hi!
Can me help with problem?

> Could not resolve all dependencies for configuration ':app:_x1DebugCompile'.
   > Could not find org.scala-lang:scala-library:2.11.6.
     Searched in the following locations:
         file:/home/alexander/sdk/android/extras/android/m2repository/org/scala-lang/scala-library/2.11.6/scala-library-2.11.6.pom
         file:/home/alexander/sdk/android/extras/android/m2repository/org/scala-lang/scala-library/2.11.6/scala-library-2.11.6.jar
         file:/home/alexander/sdk/android/extras/google/m2repository/org/scala-lang/scala-library/2.11.6/scala-library-2.11.6.pom
         file:/home/alexander/sdk/android/extras/google/m2repository/org/scala-lang/scala-library/2.11.6/scala-library-2.11.6.jar

I make project with command "gradle build"

**Comment by cdsap** [comment]
@ulx which repos are you using?

**Comment by ulx** [comment]
I using config
 
buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath "com.android.tools.build:gradle:1.2.3"
        classpath "jp.leafytree.gradle:gradle-android-scala-plugin:1.4"
    }
}

repositories {
    jcenter()
}

**Comment by cdsap** [comment]
The error says dependency is not found in your local google repository, and should search the dependency in maven/jcenter. 
If you define the repository in the root build.gradle you have to add:

```
allprojects {
    repositories {
        jcenter()
    }
}
```

**Comment by ulx** [comment]
Thanks!!
