### ISSUE TITLE
DrawerLayout$LockMode not found

### ISSUE THREAD

**Issue by Nutomic** [saturday06/gradle-android-scala-plugin#64]
```
* What went wrong:
Execution failed for task ':app:compileDebugScala'.
> Class file for android.support.v4.widget.DrawerLayout$LockMode not found
```

This happens with dependency `com.android.support:appcompat-v7:22.2.0`. 22.1.0 works, though.

Scala: 2.11.6
Gradle: 2.2.1
Android Plugin: 1.1.3
compileSdkVersion: 22
buildToolsVersion: 22.0.1

**Comment by ulx** [comment]
I think that add support  scala 2.11.7
see https://github.com/pfn/android-sdk-plugin/issues/173

**Comment by Nutomic** [comment]
You're right, it works with Scala 2.11.7 :)
