### ISSUE TITLE
Making a fat jar for android library

### ISSUE THREAD

**Issue by goboss** [saturday06/gradle-android-scala-plugin#65]
Hi,
I'm working on android library project and everything works great, but now my client requested that I create a jar with all the required dependencies (scala-library etc.) included instead of instructing him to add those to his gradle.build. I'm unfortunately not very familiar with gradle or android development in general so even after much googling I was unable to find a solution. Any suggestions?

Thanks a lot!

**Comment by saturday06** [comment]
I'm using [jarjar](https://github.com/shevek/jarjar) to make all-in-one jar.

Please see following example for Gradle.
https://github.com/shevek/jarjar/blob/master/jarjar-gradle/example/build.gradle

**Comment by goboss** [comment]
Looks great. I will give it a try.
