### ISSUE TITLE
Sample projects does not work at all

### ISSUE THREAD

**Issue by lovesuper** [saturday06/gradle-android-scala-plugin#83]
I have git cloned your repo to my disk. Opened it in my Android Studio 2.0 and have some problems with building sample projects. Errors are:
- Error:Gradle version 2.2 is required. Current version is 2.12. If using the gradle wrapper, try editing the distributionUrl in /Users/user/Documents/gradle-android-scala-plugin/sample/hello/gradle/wrapper/gradle-wrapper.properties to gradle-2.2-all.zip.

then some workaround helped me to fix that. But I faced with this error:
- Error:(17, 0) Could not find matching constructor for: org.gradle.api.internal.tasks.DefaultScalaSourceSet(java.lang.String, org.gradle.api.internal.file.BaseDirFileResolver)

**Comment by varis** [comment]
have the same problem

**Comment by jhegedus42** [comment]
have the same problem :(

**Comment by jhegedus42** [comment]
added an SOF question on this topic : http://stackoverflow.com/questions/38797662/gradle-android-scala-plugin-example-in-android-studio-gives-could-not-find-matc

**Comment by xingda920813** [comment]
Use version 1.5, version 1.4 seems to be unable to support new Gradle Plugin versions.

**Comment by xingda920813** [comment]
I just uploaded a new version to GitPack.

It supports Android Gradle Plugin 2.3.0-beta2 and Gradle 3.3.

In your project build.gradle:

buildscript {
    repositories {
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.0-beta2'
        classpath 'com.github.xingda920813:gradle-android-scala-plugin:java8'
    }
}
